- name: Setup Pacemaker Cluster
  hosts: cluster_nodes
  become: yes

  roles:
    - configure_os
    - install_pacemaker
    - setup_cluster
    - create_floating_ip
    - configure_apache
    - create_apache_resource
    - create_constraints
    - configure_drbd
    - create_drbd_promotable
